---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.4.0
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/owenlamont/uv-secure
    rev: 0.14.1
    hooks:
      - id: uv-secure
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/pylint-dev/pylint
    rev: v4.0.2
    hooks:
      - id: pylint
        args: ["--errors-only", "--rcfile=/dev/null"]
        additional_dependencies:
          - "textual>=6.4.0"
          - "miniflux>=1.1.4"
          - "html2text>=2025.4.15"
          - "pytest>=8.0.0"
