---
# From https://google.github.io/osv-scanner/github-action/
name: OSV-Scanner Vulnerability Scan

on:
  # Change "main" to your default branch if you use a different name
  # i.e. "master"
  push:
    branches: [main]
    paths:
      - 'pyproject.toml'
      - 'uv.lock'
      - 'fuzz/**'
      - '.github/workflows/osv-scanner.yml'
  pull_request:
    branches: [main]
    paths:
      - 'pyproject.toml'
      - 'uv.lock'
      - 'fuzz/**'
      - '.github/workflows/osv-scanner.yml'
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch: { }

permissions:
  contents: read

jobs:
  scan-scheduled:
    permissions:
      # Required to upload SARIF file to CodeQL.
      # See: https://github.com/github/codeql-action/issues/2117
      actions: read
      # Require writing security events to upload SARIF file to security tab
      security-events: write
      # Only need to read contents
      contents: read
    # v2.2.3
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@e92b5d07338d4f0ba0981dffed17c48976ca4730
