---
name: Scorecard analysis

on:
  branch_protection_rule:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest

    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Needed to publish results and get a badge (see `publish_results` below).
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd719bcc41092186ec7271e2924ecd7d5c6e7e  # main
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@62b2cac7ed8198426c4da30cfc0df140821a1d89  # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          # (Optional) "write" permissions required to publish results.
          # Uncomment to enable branch protection enforcement.
          publish_results: true

      - name: Upload results to code-scanning
        uses: github/codeql-action/upload-sarif@461b3a0906d1a6b1c92f1f21cd4a06b0b24e6a6e  # v3
        with:
          sarif_file: results.sarif
